[project]
<<<<<<< HEAD
name = "ci_board"
version = "0.1.3"
=======
name = "ci-board"
version = "v0.1.2"
description = "杂鱼♡～本喵设计的高扩展性剪贴板监控包喵～"
readme = "README.md"
requires-python = ">=3.8"
>>>>>>> main
authors = [
    { name="StanleyUKN", email="stanley09537000@gmail.com" },
]
description = "A clipboard monitoring library for Windows"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
]
dependencies = []